<?php

return [
    'object' => 'payment',
    'id' => 'pay_nlk1dyhiot5ks61r',
    'dateCreated' => '2025-02-16',
    'customer' => 'cus_000006519801',
    'paymentLink' => null,
    'value' => 2222,
    'netValue' => 2221.01,
    'originalValue' => null,
    'interestValue' => null,
    'description' => 'teste',
    'billingType' => 'PIX',
    'canBePaidAfterDueDate' => true,
    'pixTransaction' => null,
    'status' => 'PENDING',
    'dueDate' => '2025-02-21',
    'originalDueDate' => '2025-02-21',
    'paymentDate' => null,
    'clientPaymentDate' => null,
    'installmentNumber' => null,
    'invoiceUrl' => 'https://sandbox.asaas.com/i/nlk1dyhiot5ks61r',
    'invoiceNumber' => '07681277',
    'externalReference' => null,
    'deleted' => false,
    'anticipated' => false,
    'anticipable' => false,
    'creditDate' => null,
    'estimatedCreditDate' => null,
    'transactionReceiptUrl' => null,
    'nossoNumero' => '10621631',
    'bankSlipUrl' => 'https://sandbox.asaas.com/b/pdf/nlk1dyhiot5ks61r',
    'lastInvoiceViewedDate' => null,
    'lastBankSlipViewedDate' => null,
    'discount' => [],
    'fine' => [],
    'interest' => [],
    'postalService' => false,
    'custody' => null,
    'refunds' => null,
];
